name: real_estate_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Style And Widgets
  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0
  fluttertoast: ^8.2.2

  # App Controller And Helpers
  flutter_bloc: ^8.1.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1

  # Remote Network
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # App Analyzer
  lint: ^2.1.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  # App Assets
  assets:
    - assets/images/
    - assets/icons/